version: "3.7"

# generate a jwt secret with the following command
# # openssl rand -hex 32 | tr -d "\n" > "jwt.hex"
services:
  erigon:
    build: .
    command: >
     erigon
       --http.api "eth"
       --http.trace
       --http.addr "0.0.0.0"
       --http.port "8545"
       --datadir "/home/erigon/app/data"
       --authrpc.jwtsecret "/home/erigon/app/jwtsecret"
    ports:
      - "127.0.0.1:8545:8545"
    volumes:
      - ./erigon_data:/home/erigon/app/data:rw
      - ./jwt.hex:/home/erigon/app/jwtsecret:ro

  # TODO make nginx work
  nginx:
    image: nginx:1.21
    environment:
      - NGINX_PORT=80 # default port
    ports:
      - "6969:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
