# Use the official Python image from DockerHub
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the Python script into the container
COPY blue.py .

# Run the Python script
CMD ["python", "./blue.py"]
