version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./.docker_data/ipfs:/ipfsdata
    ports:
      - "4001:4001" # for swarm
      - "127.0.0.1:8080:8080" # gateway
      - "127.0.0.1:8081:8081" # websocket
      - "127.0.0.1:5001:5001" # api server

  nginx:
    image: nginx:1.21
    environment:
      - NGINX_PORT=80 # default port
    ports:
      - "6969:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
