version: "3.3"
services:
  db:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    env_file:
      - .env # configure postgres
    volumes:
      - ${PWD}/.db_data:/var/lib/postgresql/data/
      - ${PWD}/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5055:5055"
    depends_on:
      - db
    env_file:
      - .env
