version: "3.3"
services:
  db:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    env_file:
      - .env # configure postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5055:5055"
    depends_on:
      - db
    env_file:
      - .env
