version: "3.7"
services:
  redis:
    image: redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PW}
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/redis_data:/data

volumes:
  redis_data:
